# Kitty config

# Font
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14
disable_ligatures always
macos_thicken_font 0
text_composition_strategy legacy
modify_font cell_height 1px
modify_font cell_width -1px
window_padding_width 4

# Remote control
allow_remote_control yes
listen_on unix:/tmp/kitty

# Cursor
cursor_shape     block
cursor_blink_interval 0

# Layout - splits layout required for vsplit/hsplit to work
enabled_layouts splits,stack

# Window
background_opacity 1.0
background_blur 0
remember_window_size yes
remember_window_position yes
hide_window_decorations no
confirm_os_window_close 0

# Scrollback
scrollback_lines 10000000

# Bell
enable_audio_bell no
visual_bell_duration 0

# Mouse
mouse_hide_wait 3.0
copy_on_select clipboard
detect_urls yes
open_url_with default
mouse_map cmd+left release ungrabbed,grabbed mouse_handle_click link

# Shell
shell_integration no-cursor

# Tab bar
tab_bar_style separator

# macOS
macos_colorspace srgb
macos_option_as_alt no
macos_quit_when_last_window_closed no
macos_titlebar_color #282c34

# Keybindings
map cmd+, launch --type=tab open -t ~/.config/kitty/kitty.conf
map cmd+r clear_terminal scroll active
map cmd+t new_tab_with_cwd
map cmd+shift+t new_tab
map cmd+] next_window
map cmd+[ previous_window
map cmd+f show_scrollback
map cmd+p kitten hints --type linenum
map cmd+w combine : close_window : kitten equalize.py
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map cmd+k clear_terminal clear active
map cmd+enter toggle_fullscreen
map cmd+shift+enter toggle_layout stack
map cmd+d combine : goto_layout splits : launch --location=vsplit --cwd=current : kitten equalize.py v
map cmd+shift+d combine : goto_layout splits : launch --location=hsplit --cwd=current : kitten equalize.py h

# BEGIN_KITTY_THEME
# One Dark
include current-theme.conf
# END_KITTY_THEME
